sudo: false
language: perl
perl:
  - "5.22"
  #- "5.20"
  #- "5.18"
  #- "5.16"
  #- "5.14"
  #- "5.12"
os:
  - linux
before_install:
  - "cpanm Module::Build::WithXSpp"
  - "cpanm ExtUtils::Typemaps::ObjectMap"
compiler:
  - gcc
install:
  - echo "$CXX"
  - export CXX="g++-4.8" CC="gcc-4.8"
  #- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - echo "$CXX"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
